const products = {
  discountedProducts: [
    {
        id: 1,
        name: 'Tủ lạnh Samsung Inverter 680 lít ABC',
        category: 'TỦ LẠNH',
        discount: 23,
        priceOld: '18.500.000đ',
        priceNew: '14.200.000đ',
        image: '/assets/images/tulanhSamsung-1.jpg',
      },
      {
        id: 2,
        name: 'Điều hòa 1 chiều Inverter LG V10WIN',
        category: 'ĐIỀU HÒA - MÁY LẠNH',
        discount: 12,
        priceOld: '8.200.000đ',
        priceNew: '7.200.000đ',
        image: '/assets/images/dieuhoa1chieu.jpg',
      },
      {
        id: 2,
        name: 'Điều hòa 1 chiều Inverter LG V10WIN',
        category: 'ĐIỀU HÒA - MÁY LẠNH',
        discount: 12,
        priceOld: '8.200.000đ',
        priceNew: '7.200.000đ',
        image: '/assets/images/dieuhoa1chieu-2.jpg',
      },
      {
        id: 2,
        name: 'Điều hòa 1 chiều Inverter LG V10WIN',
        category: 'ĐIỀU HÒA - MÁY LẠNH',
        discount: 12,
        priceOld: '8.200.000đ',
        priceNew: '7.200.000đ',
        image: '/assets/images/dieuhoa1chieu-3.jpg',
      },
      {
        id: 2,
        name: 'Điều hòa 1 chiều Inverter LG V10WIN',
        category: 'ĐIỀU HÒA - MÁY LẠNH',
        discount: 12,
        priceOld: '8.200.000đ',
        priceNew: '7.200.000đ',
        image: '/assets/images/dieuhoa1chieu-4.jpg',
      },
    ],
    promotionalProducts: [
        {
            id: 1,
            name: 'Tủ lạnh Samsung Inverter 680 lít ABC',
            category: 'TỦ LẠNH',
            discount: 20,
            priceOld: '18.500.000đ',
            priceNew: '14.200.000đ',
            image: '/assets/images/tulanhSamsung-1.jpg',
          },
          {
            id: 2,
            name: 'Điều hòa 1 chiều Inverter LG V10WIN',
            category: 'ĐIỀU HÒA - MÁY LẠNH',
            discount: 16,
            priceOld: '8.200.000đ',
            priceNew: '7.200.000đ',
            image: '/assets/images/dieuhoa1chieu.jpg',
          },
          {
            id: 2,
            name: 'Điều hòa 1 chiều Inverter LG V10WIN',
            category: 'ĐIỀU HÒA - MÁY LẠNH',
            discount: 18,
            priceOld: '8.200.000đ',
            priceNew: '7.200.000đ',
            image: '/assets/images/dieuhoa1chieu-2.jpg',
          },
          {
            id: 2,
            name: 'Điều hòa 1 chiều Inverter LG V10WIN',
            category: 'ĐIỀU HÒA - MÁY LẠNH',
            discount: 22,
            priceOld: '8.200.000đ',
            priceNew: '7.200.000đ',
            image: '/assets/images/dieuhoa1chieu-3.jpg',
          },
          {
            id: 2,
            name: 'Điều hòa 1 chiều Inverter LG V10WIN',
            category: 'ĐIỀU HÒA - MÁY LẠNH',
            discount: 12,
            priceOld: '8.200.000đ',
            priceNew: '7.200.000đ',
            image: '/assets/images/dieuhoa1chieu-4.jpg',
          },
    ]
    
};

export default products